const { withXcodeProject } = require('@expo/config-plugins');

/**
 * Guarantee full dSYM generation and un-stripped symbols so Xcode
 * Instruments can map `com.apple.audio.IOThread` stack frames back to Swift
 * function names (AudioEngineManager.makeBinauralNode, etc.).
 *
 * Why a config plugin rather than editing the Xcode project directly:
 * `ios/` is gitignored and regenerated by `expo prebuild`, so any manual
 * pbxproj edit is destroyed on the next prebuild. This re-applies on every
 * generation.
 *
 * Settings applied to ALL build configurations:
 *   DEBUG_INFORMATION_FORMAT = dwarf-with-dsym
 *       Xcode's Release default is already dwarf-with-dsym, but it is not
 *       written explicitly in the Expo-generated project — so we pin it
 *       rather than inherit an unstated default.
 *   COPY_PHASE_STRIP / STRIP_INSTALLED_PRODUCT = NO
 *       Keeps symbol names in the installed binary. Instruments can
 *       symbolicate from a dSYM alone, but an un-stripped binary removes an
 *       entire class of "why is this frame just a hex address" failure while
 *       profiling on device.
 *
 * This affects symbol tables only — it does not change optimization level,
 * so Release profiling numbers stay representative of shipped performance.
 */
const withDebugSymbols = (config) =>
  withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const configurations = project.pbxXCBuildConfigurationSection();

    for (const key of Object.keys(configurations)) {
      const entry = configurations[key];
      if (!entry || typeof entry !== 'object' || !entry.buildSettings) continue;

      entry.buildSettings.DEBUG_INFORMATION_FORMAT = '"dwarf-with-dsym"';
      entry.buildSettings.COPY_PHASE_STRIP = 'NO';
      entry.buildSettings.STRIP_INSTALLED_PRODUCT = 'NO';
    }

    return cfg;
  });

module.exports = withDebugSymbols;
